Repository GDSC-IIIT-Kalyani/hacktober-leaderboard, pull requests merged in 2022-10, with the labels that each got.

#43 verify and merge k3ys-branch to dev
  .gitignore
  .vscode/settings.json
  README.md
  assets/Group 1.svg
  assets/Line 1.svg
  assets/Logo-2-Color 1.svg
  assets/favicon/android-icon-144x144.png
  assets/favicon/android-icon-192x192.png
  assets/favicon/android-icon-36x36.png
  assets/favicon/android-icon-48x48.png
  assets/favicon/android-icon-72x72.png
  assets/favicon/android-icon-96x96.png
  assets/favicon/apple-icon-114x114.png
  assets/favicon/apple-icon-120x120.png
  assets/favicon/apple-icon-144x144.png
  assets/favicon/apple-icon-152x152.png
  assets/favicon/apple-icon-180x180.png
  assets/favicon/apple-icon-57x57.png
  assets/favicon/apple-icon-60x60.png
  assets/favicon/apple-icon-72x72.png
  assets/favicon/apple-icon-76x76.png
  assets/favicon/apple-icon-precomposed.png
  assets/favicon/apple-icon.png
  assets/favicon/browserconfig.xml
  assets/favicon/favicon-16x16.png
  assets/favicon/favicon-32x32.png
  assets/favicon/favicon-96x96.png
  assets/favicon/favicon.ico
  assets/favicon/manifest.json
  assets/favicon/ms-icon-144x144.png
  assets/favicon/ms-icon-150x150.png
  assets/favicon/ms-icon-310x310.png
  assets/favicon/ms-icon-70x70.png
  assets/image 11.svg
  assets/image 13.svg
  assets/image 4.svg
  assets/nathan-van-egmond-0IwypLLbHiA-unsplash.jpg
  static/script.js
  static/style.css
  templates/leaderboard.html
Labels: hacktoberfest, hacktoberfest-ready, hacktoberfest-accepted

#44 add auth in api wrapper and repo list function
  .env.sample
  .gitignore
  api/github.py
  app.py
  data2.json
  img/MediCare.png
  img/Placement Portal 1.png
  img/full logo.png
  img/gdsc.png
  img/paperVault.png
  img/thor.jpg
  img/todo tracker.jpg
  img/whatsapp filter.png
  img/woc certificate generator.jpg
  requirements.txt
  static/data2.json
Labels: hacktoberfest, hacktoberfest-ready, hacktoberfest-accepted

#45 Dev to main
  .env.sample
  .gitignore
  .vscode/settings.json
  README.md
  api/github.py
  app.py
  assets/Group 1.svg
  assets/Line 1.svg
  assets/Logo-2-Color 1.svg
  assets/favicon/android-icon-144x144.png
  assets/favicon/android-icon-192x192.png
  assets/favicon/android-icon-36x36.png
  assets/favicon/android-icon-48x48.png
  assets/favicon/android-icon-72x72.png
  assets/favicon/android-icon-96x96.png
  assets/favicon/apple-icon-114x114.png
  assets/favicon/apple-icon-120x120.png
  assets/favicon/apple-icon-144x144.png
  assets/favicon/apple-icon-152x152.png
  assets/favicon/apple-icon-180x180.png
  assets/favicon/apple-icon-57x57.png
  assets/favicon/apple-icon-60x60.png
  assets/favicon/apple-icon-72x72.png
  assets/favicon/apple-icon-76x76.png
  assets/favicon/apple-icon-precomposed.png
  assets/favicon/apple-icon.png
  assets/favicon/browserconfig.xml
  assets/favicon/favicon-16x16.png
  assets/favicon/favicon-32x32.png
  assets/favicon/favicon-96x96.png
  assets/favicon/favicon.ico
  assets/favicon/manifest.json
  assets/favicon/ms-icon-144x144.png
  assets/favicon/ms-icon-150x150.png
  assets/favicon/ms-icon-310x310.png
  assets/favicon/ms-icon-70x70.png
  assets/image 11.svg
  assets/image 13.svg
  assets/image 4.svg
  assets/nathan-van-egmond-0IwypLLbHiA-unsplash.jpg
  data2.json
  img/MediCare.png
  img/Placement Portal 1.png
  img/full logo.png
  img/gdsc.png
  img/paperVault.png
  img/thor.jpg
  img/todo tracker.jpg
  img/whatsapp filter.png
  img/woc certificate generator.jpg
  requirements.txt
  static/data2.json
  static/script.js
  static/style.css
  templates/leaderboard.html
Labels: hacktoberfest

#46 add token auth and fix repo topics filter
  api/github.py
Labels: hacktoberfest, hacktoberfest-ready, hacktoberfest-accepted

#55 access token from .env
  .gitignore
  app.py
  requirements.txt
  static/data2.json
Labels: hacktoberfest, hacktoberfest-ready, hacktoberfest-accepted

#58 Add project cards and fixed marquee text, fix all conflicts
  static/style.css
  templates/New folder/index.html
  templates/New folder/leaderboard.html
  templates/New folder/projects.html
  templates/index.html
  templates/leaderboard.html
Labels: hacktoberfest, hacktoberfest-ready, hacktoberfest-accepted

#60 jinja added, all good only project section remaining
  app.py
  static/assets/Group 1.svg
  static/assets/Line 1.svg
  static/assets/Logo-2-Color 1.svg
  static/assets/favicon/android-icon-144x144.png
  static/assets/favicon/android-icon-192x192.png
  static/assets/favicon/android-icon-36x36.png
  static/assets/favicon/android-icon-48x48.png
  static/assets/favicon/android-icon-72x72.png
  static/assets/favicon/android-icon-96x96.png
  static/assets/favicon/apple-icon-114x114.png
  static/assets/favicon/apple-icon-120x120.png
  static/assets/favicon/apple-icon-144x144.png
  static/assets/favicon/apple-icon-152x152.png
  static/assets/favicon/apple-icon-180x180.png
  static/assets/favicon/apple-icon-57x57.png
  static/assets/favicon/apple-icon-60x60.png
  static/assets/favicon/apple-icon-72x72.png
  static/assets/favicon/apple-icon-76x76.png
  static/assets/favicon/apple-icon-precomposed.png
  static/assets/favicon/apple-icon.png
  static/assets/favicon/browserconfig.xml
  static/assets/favicon/favicon-16x16.png
  static/assets/favicon/favicon-32x32.png
  static/assets/favicon/favicon-96x96.png
  static/assets/favicon/favicon.ico
  static/assets/favicon/manifest.json
  static/assets/favicon/ms-icon-144x144.png
  static/assets/favicon/ms-icon-150x150.png
  static/assets/favicon/ms-icon-310x310.png
  static/assets/favicon/ms-icon-70x70.png
  static/assets/image 11.svg
  static/assets/image 13.svg
  static/assets/image 4.svg
  static/assets/nathan-van-egmond-0IwypLLbHiA-unsplash.jpg
  static/style.css
  templates/lb.html
  templates/projects.html
Labels: hacktoberfest, hacktoberfest-ready, hacktoberfest-accepted

#69 Change marquee font
  templates/lb.html
Labels: hacktoberfest, level-1, hacktoberfest-ready, hacktoberfest-accepted

#76 feat: add footer
  static/footer.css
  static/style.css
  templates/lb.html
Labels: hacktoberfest-accepted

#79 Added Hacktoberfest link webpage
  Hacktoberfest link/index.html
  Hacktoberfest link/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#80 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted
